dist: xenial

language: crystal

crystal:
  - latest

cache: shards

script:
  - shards install
  - crystal spec
  - shards build --production --release --no-debug

notifications:
  email:
    recipients:
      - mkdika@gmail.com
    on_failure: always
